# Generated by Django 3.0.5 on 2020-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMapInfo',
            fields=[
                ('id', models.IntegerField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('lng', models.FloatField(max_length=16)),
                ('lat', models.FloatField(max_length=16)),
                ('is_open', models.BooleanField(default=False)),
                ('open_time', models.CharField(max_length=16)),
                ('note', models.CharField(max_length=16)),
            ],
        ),
    ]
